name: Build and Upload JAR to Google Cloud Storage

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package
      # Ensure this command correctly targets your project's build process

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCS_SA_KEY }}

    - name: Upload JAR file to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: /home/runner/work/Jabberpoint-Software-Quality/Jabberpoint-Software-Quality/target/JabberPoint-Software-Quality-SNAPSHOT.jar
        destination: gs://production_jar_bucket/JabberPoint-Software-Quality-SNAPSHOT.jar
        # Adjust the path and destination as needed

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: JabberPoint-Software-Quality-SNAPSHOT.jar
        path: /home/runner/work/Jabberpoint-Software-Quality/Jabberpoint-Software-Quality/target/JabberPoint-Software-Quality-SNAPSHOT.jar
