name: Build and Upload JAR to Google

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
        

    - name: Build with Maven
      run: mvn -B test --file pom.xml
      

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCS_SA_KEY }}

    - name: Upload JAR file to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ${{ github.workspace }}
        destination: 
     

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 
        path: 
